//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppServices.IntService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntService.IIntService")]
    public interface IIntService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntService/AddInts", ReplyAction="http://tempuri.org/IIntService/AddIntsResponse")]
        MathServices.Messages.AddIntsResponse AddInts(MathServices.Messages.AddIntsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntService/AddInts", ReplyAction="http://tempuri.org/IIntService/AddIntsResponse")]
        System.Threading.Tasks.Task<MathServices.Messages.AddIntsResponse> AddIntsAsync(MathServices.Messages.AddIntsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntServiceChannel : AppServices.IntService.IIntService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntServiceClient : System.ServiceModel.ClientBase<AppServices.IntService.IIntService>, AppServices.IntService.IIntService {
        
        public IntServiceClient() {
        }
        
        public IntServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MathServices.Messages.AddIntsResponse AddInts(MathServices.Messages.AddIntsRequest request) {
            return base.Channel.AddInts(request);
        }
        
        public System.Threading.Tasks.Task<MathServices.Messages.AddIntsResponse> AddIntsAsync(MathServices.Messages.AddIntsRequest request) {
            return base.Channel.AddIntsAsync(request);
        }
    }
}
